version: '3.8'
services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: pg_db
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pwd
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: